export const REQUEST_QUESTION_DATA = 'REQUEST_QUESTION_DATA';
export const LOADING_QUESTION_DATA = 'LOADING_QUESTION_DATA';
export const RECEIVE_QUESTION_DATA = 'RECEIVE_QUESTION_DATA';
export const ERROR_QUESTION_DATA = 'ERROR_QUESTION_DATA';
